version: "3.4"
services:
  database:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - "${HOME}/Desktop/postgres:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"

  log_creator_1:
    container_name: log_creator_1
    build:
      context: webapp
      dockerfile: Dockerfile
      target: prod
    environment:
      SEND_TO_URL: "http://log_creator_2:3001/"
      PORT: 3000
    ports:
      - "3000:3000"

  log_creator_2:
    container_name: log_creator_2
    build:
      context: webapp
      dockerfile: Dockerfile
      target: prod
    environment:
      SEND_TO_URL: "http://log_creator_1:3000/"
      PORT: 3001
    ports:
      - "3001:3001"
