version: "3.4"
services:
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - webapp-database
    ports:
      - "3000:3000"
  webapp-database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db