version: "3.4"
services:
  database:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    ports:
      - "5432:5432"

  log_creator_1:
    container_name: log_creator_1
    build:
      context: log_creator
      dockerfile: Dockerfile
      target: prod
    environment:
      SEND_TO_URL: "http://log_creator_2:3001/"
      PORT: 3002
    ports:
      - "3002:3002"

  log_creator_2:
    container_name: log_creator_2
    build:
      context: log_creator
      dockerfile: Dockerfile
      target: prod
    environment:
      SEND_TO_URL: "http://log_creator_1:3002/"
      PORT: 3001
    ports:
      - "3001:3001"
