version: "3.4"
services:
  database:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teamrocket_db
    ports:
      # using 5433 to avoid conflict with default port on dev machines
      - "5433:5433"

  log_creator_1:
    container_name: log_creator_1
    build:
      context: log_creator
      dockerfile: Dockerfile
      target: prod
    environment:
      SEND_TO_URL: "http://log_creator_2:3001/"
      PORT: 3002
    ports:
      - "3002:3002"

  log_creator_2:
    container_name: log_creator_2
    build:
      context: log_creator
      dockerfile: Dockerfile
      target: prod
    environment:
      SEND_TO_URL: "http://log_creator_1:3002/"
      PORT: 3001
    ports:
      - "3001:3001"

  logging_server:
    container_name: logging_server
    build:
      context: logging_server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:password@database:5433/teamrocket_db
    ports:
      - "3000:3000"
